// react/src/components/RightList.jsx
import Empty from './Empty'
function RightList({ participants, excludeParticipant }) {
    return (
        <div className="col-12 col-md-6">
            {
                participants.length == 0 ? <Empty /> :
                    <ul className="list-group list-group-flush">
                        {
                            participants.map(p => (
                                <li key={p.id} className="list-group-item d-flex justify-content-between">
                                    <button className='btn btn-sm btn-primary' onClick={() => excludeParticipant(p.id)} >
                                        <span className='bi bi-chevron-left'></span>
                                    </button>
                                    <span>{p.firstName} {p.lastName}</span>
                                </li>
                            ))
                        }
                    </ul>
            }
        </div>
    );
}

export default RightList;

// vue/src/components/RightList.vue
<template>
    <div class="col-12 col-md-6">
        <Empty v-if="participants.length == 0" />
        <ul v-else class="list-group list-group-flush">
            <li v-for="p in participants" class="list-group-item d-flex justify-content-between">
                <button class="btn btn-sm btn-primary" @click="exclude(p.id)">
                    <span class="bi bi-chevron-left"></span>
                </button>
                <span>{{ p.firstName }} {{ p.lastName }}</span>
            </li>
        </ul>
    </div>
</template>

<script>
import Empty from "./Empty.vue";
export default {
    name: "RightList",
    emits: ["onExcluded"],
    components: {
        Empty
    },
    props: {
        participants: {
            type: Array
        }
    },
    methods: {
        exclude(id) {
            this.$emit("onExcluded", id);
        }
    }
}
</script>
