// vue/src/components/LeftList.vue
<template>
    <div class="col-12 col-md-6">
        <Empty v-if="participants.length == 0" />
        <ul v-else class="list-group list-group-flush">
            <li v-for="p in participants" class="list-group-item d-flex justify-content-between">
                <span>{{ p.firstName }} {{ p.lastName }}</span>
                <button class="btn btn-sm btn-primary" @click="select(p.id)">
                    <span class="bi bi-chevron-right"></span>
                </button>
            </li>
        </ul>
    </div>
</template>

<script>
import Empty from "./Empty.vue";
export default {
    name: "LeftList",
    emits: ["onSelected"],
    components: {
        Empty
    },
    props: {
        participants: {
            type: Array
        }
    },
    methods: {
        select(id) {
            this.$emit("onSelected", id);
        }
    }
}
</script>

// react/src/components/LeftList.jsx
import Empty from './Empty'

/*
array map fonsksiyonu bir dizi içindeki öğeleri başka bir forma dönüştürme yoludur:

C# => yield return
*/
function LeftList({ participants, selectParticipant }) {
    return (
        <div className="col-12 col-md-6">
            {participants.length == 0 ? <Empty /> :
                <ul className="list-group list-group-flush">
                    {participants.map(p => (
                        <li key={p.id} className="list-group-item d-flex justify-content-between">
                            <span>{p.firstName} {p.lastName}</span>
                            <button className='btn btn-sm btn-primary' onClick={() => selectParticipant(p.id)}>
                                <span className='bi bi-chevron-right'></span>
                            </button>
                        </li>))}
                </ul>
            }
        </div>);
}

export default LeftList;
